name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    defaults:
      run:
        working-directory: website
    runs-on: ubuntu-20.04
    permissions:
      # needs to git diff the repo
      contents: write
      # write artifacts and comment on pr related to this
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
          cname: roamingthings.de
